### ISSUE TITLE
Useful Chat Commands 1.0

### ISSUE THREAD

**Issue by bmx22c** [openplanet-nl/plugin-signing#145]
## Plugin description
This plugin depends on Better Chat and add some useful chat commands.

## Did you provide a `perms` meta value or a `#perms` preprocessor option?
no

## Did you use `Permissions.as`?
no

## Attach your plugin
[UsefulChatCommands.zip](https://github.com/openplanet-nl/plugin-signing/files/7748830/UsefulChatCommands.zip)

**Comment by bmx22c** [comment]
I updated the plugin in the meantime. That's why I closed and reopened the issue :)

**Comment by codecat** [comment]
You forgot to call `BetterChat::UnregisterCommand` on plugin destruction. Not a big deal but it's good to make sure this happens.

**Comment by bmx22c** [comment]
I can't test my new code atm but it should be the right way to do it :)
Thanks for the tip !
[UsefulChatCommands.zip](https://github.com/openplanet-nl/plugin-signing/files/7776186/UsefulChatCommands.zip)

**Comment by codecat** [comment]
Sorry for the delay 👍 

[UsefulChatCommands.zip](https://github.com/openplanet-nl/plugin-signing/files/7792748/UsefulChatCommands.zip)
